# -*- coding: utf-8 -*-
"""aula_modo_interativo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LBpDu87IPJLoJA2GS-yndiEDqIAhzfUA

Modo Interativo do phyton
"""

# Invoca o sistema de ajuda integrado, nele posso passar parametros para informar como usar um metodo, classe ou função
# Dentro deste modo você pode consultar como usar um determinado parametro
help()

# Função dir() retorna a lista de nomes no escopo local
dir()

# Passando o valor inteiro 100 ele retorna todos os metodos do argumento 100
dir(100)

